In [372]:
import os

print(os.getcwd())

c:\Users\Ayushi Sinha\Downloads\DATAproject\ecommerce-ai-analyst\Notebooks\notebooks

In [373]:
import pandas as pd
orders = pd.read_csv("../../data/raw/olist_orders_dataset.csv")

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-10-2017 10:56,02-10-2017 11:07,04-10-2017 19:55,10-10-2017 21:25,18-10-2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24-07-2018 20:41,26-07-2018 03:24,26-07-2018 14:31,07-08-2018 15:27,13-08-2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08-08-2018 08:38,08-08-2018 08:55,08-08-2018 13:50,17-08-2018 18:06,04-09-2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18-11-2017 19:28,18-11-2017 19:45,22-11-2017 13:39,02-12-2017 00:28,15-12-2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13-02-2018 21:18,13-02-2018 22:20,14-02-2018 19:46,16-02-2018 18:17,26-02-2018 00:00

In [374]:
orders.shape

(99441, 8)

In [375]:
orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,09-03-2017 09:54,09-03-2017 09:54,10-03-2017 11:18,17-03-2017 15:08,28-03-2017 00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,06-02-2018 12:58,06-02-2018 13:10,07-02-2018 23:22,28-02-2018 17:37,02-03-2018 00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,27-08-2017 14:46,27-08-2017 15:04,28-08-2017 20:52,21-09-2017 11:24,27-09-2017 00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,08-01-2018 21:28,08-01-2018 21:36,12-01-2018 15:35,25-01-2018 23:32,15-02-2018 00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,08-03-2018 20:57,09-03-2018 11:20,09-03-2018 22:11,16-03-2018 13:08,03-04-2018 00:00

In [376]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [377]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [378]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [379]:
(orders.isnull().sum() / len(orders)) * 100

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [380]:
orders.duplicated().sum()

np.int64(0)

In [381]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [382]:
orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,88789,50462,61544,75649,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-08-2018 12:06,10-01-2018 10:32,09-05-2018 15:48,11-12-2017 18:52,20-12-2017 00:00
freq,1,1,96478,28,109,47,7,522

In [383]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [384]:
(orders.isnull().sum() / len(orders) * 100).round(2)

order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
dtype: float64

In [385]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

C:\Users\Ayushi Sinha\AppData\Local\Temp\ipykernel_12488\973292169.py:10: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [386]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [387]:
orders_clean = orders.copy()

In [388]:
orders_clean.shape

(99441, 8)

In [389]:
orders_clean.groupby("order_status")[
    [
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].apply(lambda x: x.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,1,2,2
canceled,432,593,623
created,5,5,5
delivered,58014,59605,60126
invoiced,170,314,314
processing,176,301,301
shipped,663,680,1107
unavailable,332,609,609

In [390]:
orders_clean.columns = orders_clean.columns.str.strip().str.lower()

In [391]:
orders_clean.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [392]:
orders_clean.to_csv(
    "../../data/processed/orders_clean.csv",
    index=False
)

In [393]:
import os

print(os.path.exists("../../data/processed/orders_clean.csv"))

True

In [394]:
customers = pd.read_csv("../../data/raw/olist_customers_dataset.csv")

In [395]:
customers.shape

(99441, 5)

In [396]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [397]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [398]:
customers.duplicated().sum()

np.int64(0)

In [399]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [400]:
customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [401]:
customers["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [402]:
customers_clean = customers.copy()

In [403]:
customers_clean.columns = customers_clean.columns.str.strip().str.lower()

In [404]:
customers_clean.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [405]:
customers_clean.to_csv(
    "../../data/processed/customers_clean.csv",
    index=False
)

In [406]:
import os

print(os.path.exists("../../data/processed/customers_clean.csv"))

True

In [407]:
order_items = pd.read_csv(
    "../../data/raw/olist_order_items_dataset.csv"
)

In [408]:
order_items.shape

(112650, 7)

In [409]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [410]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [411]:
order_items.duplicated().sum()

np.int64(0)

In [412]:
order_items["order_id"].duplicated().sum()

np.int64(13984)

In [413]:
order_items["order_item_id"].value_counts().sort_index()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [414]:
order_items[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [415]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"],
    errors="coerce"
)

In [416]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [417]:
order_items_clean = order_items.copy()

In [418]:
order_items_clean.to_csv(
    "../../data/processed/order_items_clean.csv",
    index=False
)

In [419]:
import os

print(
    os.path.exists(
        "../../data/processed/order_items_clean.csv"
    )
)

True

In [420]:
payments = pd.read_csv(
    "../../data/raw/olist_order_payments_dataset.csv"
)

In [421]:
payments.shape

(103886, 5)

In [422]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [423]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [424]:
payments.duplicated().sum()

np.int64(0)

In [425]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [426]:
payments[[
    "payment_installments",
    "payment_value"
]].describe()

       payment_installments  payment_value
count         103886.000000  103886.000000
mean               2.853349     154.100380
std                2.687051     217.494064
min                0.000000       0.000000
25%                1.000000      56.790000
50%                1.000000     100.000000
75%                4.000000     171.837500
max               24.000000   13664.080000

In [427]:
payments[payments["payment_value"] <= 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [428]:
payments_clean = payments.copy()

In [429]:
payments_clean.columns = (
    payments_clean.columns
    .str.strip()
    .str.lower()
)

In [430]:
payments_clean.to_csv(
    "../../data/processed/payments_clean.csv",
    index=False
)

In [431]:
import os

print(
    os.path.exists(
        "../../data/processed/payments_clean.csv"
    )
)

True

In [432]:
reviews = pd.read_csv(
    "../../data/raw/olist_order_reviews_dataset.csv"
)

In [433]:
reviews.shape

(99224, 7)

In [434]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [435]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [436]:
reviews.duplicated().sum()

np.int64(0)

In [437]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [438]:
reviews["review_score"].describe()

count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

In [439]:
review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in review_date_columns:
    reviews[col] = pd.to_datetime(
        reviews[col],
        errors="coerce"
    )

In [440]:
reviews_clean = reviews.copy()

In [441]:
reviews_clean.columns = (
    reviews_clean.columns
    .str.strip()
    .str.lower()
)

In [442]:
reviews_clean.to_csv(
    "../../data/processed/reviews_clean.csv",
    index=False
)

In [443]:
import os

print(
    os.path.exists(
        "../../data/processed/reviews_clean.csv"
    )
)

True

In [444]:
products = pd.read_csv(
    "../../data/raw/olist_products_dataset.csv"
)

In [445]:
products.shape

(32951, 9)

In [446]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [447]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [448]:
products.duplicated().sum()

np.int64(0)

In [449]:
products["product_id"].duplicated().sum()

np.int64(0)

In [450]:
products["product_category_name"].value_counts()

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 73, dtype: int64

In [451]:
products[
    [
        "product_name_lenght",
        "product_description_lenght",
        "product_photos_qty",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm"
    ]
].describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [452]:
products_clean = products.copy()

In [453]:
products_clean.columns = (
    products_clean.columns
    .str.strip()
    .str.lower()
)

In [454]:
products_clean.to_csv(
    "../../data/processed/products_clean.csv",
    index=False
)

In [455]:
import os

print(
    os.path.exists(
        "../../data/processed/products_clean.csv"
    )
)

True

In [456]:
sellers = pd.read_csv(
    "../../data/raw/olist_sellers_dataset.csv"
)

In [457]:
sellers.shape

(3095, 4)

In [458]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')

In [459]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [460]:
sellers.duplicated().sum()

np.int64(0)

In [461]:
sellers["seller_id"].duplicated().sum()

np.int64(0)

In [462]:
sellers["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [463]:
sellers_clean = sellers.copy()

In [464]:
sellers_clean.columns = (
    sellers_clean.columns
    .str.strip()
    .str.lower()
)

In [465]:
sellers_clean.to_csv(
    "../../data/processed/sellers_clean.csv",
    index=False
)

In [466]:
print(
    os.path.exists(
        "../../data/processed/sellers_clean.csv"
    )
)

True

In [467]:
geolocation = pd.read_csv(
    "../../data/raw/olist_geolocation_dataset.csv"
)

In [468]:
geolocation.shape

(1000163, 5)

In [469]:
geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [470]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [471]:
geolocation.duplicated().sum()

np.int64(261831)

In [472]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

In [473]:
geolocation.shape[0]

1000163

In [474]:
geolocation[
    ["geolocation_lat", "geolocation_lng"]
].describe()

       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

In [475]:
geolocation_clean = geolocation.copy()

In [476]:
geolocation_clean.columns = (
    geolocation_clean.columns
    .str.strip()
    .str.lower()
)

In [477]:
geolocation_clean.to_csv(
    "../../data/processed/geolocation_clean.csv",
    index=False
)

In [478]:
print(
    os.path.exists(
        "../../data/processed/geolocation_clean.csv"
    )
)

True

In [479]:
category_translation = pd.read_csv(
    "../../data/raw/product_category_name_translation.csv"
)

In [480]:
category_translation.shape

(71, 2)

In [481]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='str')

In [482]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [483]:
category_translation.duplicated().sum()

np.int64(0)

In [484]:
category_translation["product_category_name"].duplicated().sum()

np.int64(0)

In [485]:
category_translation_clean = category_translation.copy()

In [486]:
category_translation_clean.columns = (
    category_translation_clean.columns
    .str.strip()
    .str.lower()
)

In [487]:
category_translation_clean.to_csv(
    "../../data/processed/category_translation_clean.csv",
    index=False
)

In [488]:
print(
    os.path.exists(
        "../../data/processed/category_translation_clean.csv"
    )
)

True